const KEY='meuFluxoDados', CONFIG='meuFluxoSync';
// Preencha uma única vez antes de publicar. Não envie este arquivo a um repositório público.
const BUILT_IN_CONFIG={url:'https://script.google.com/macros/s/AKfycby4abJ66ZMLNvXGhfCPhJzZZjNxj8-5cxqR31o3ivXs58TDT4AGtN8mKWfsYgq6wHlq/exec',token:''};
const empty={budget:{salary:0,savingGoal:0,otherIncome:0,cdiRate:14.9},fixed:[],expenses:[],incomes:[],investments:[]};
let data={...empty,...JSON.parse(localStorage.getItem(KEY)||'{}')}, config={...BUILT_IN_CONFIG,...JSON.parse(localStorage.getItem(CONFIG)||'{}')}, selectedDate=new Date();
const $=s=>document.querySelector(s), money=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), id=()=>crypto.randomUUID();
function number(v){return Number(String(v||'').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.'))||0}
function key(){return `${selectedDate.getFullYear()}-${String(selectedDate.getMonth()+1).padStart(2,'0')}`}function total(a){return a.reduce((s,x)=>s+Number(x.value||0),0)}function thisMonth(a){return a.filter(x=>x.month===key())}
function persist(){localStorage.setItem(KEY,JSON.stringify(data));render();if(config.url&&config.token)syncSave()}
function render(){data={...empty,...data,budget:{...empty.budget,...data.budget},fixed:data.fixed||[],expenses:data.expenses||[],incomes:data.incomes||[],investments:data.investments||[]};const b=data.budget,monthlyIncome=total(thisMonth(data.incomes)),income=b.salary+b.otherIncome+monthlyIncome,fixed=total(data.fixed),variable=total(thisMonth(data.expenses)),free=income-b.savingGoal-fixed-variable,cdi=Math.pow(1+(b.cdiRate||0)/100,1/12)-1,invested=total(data.investments),returns=data.investments.reduce((s,x)=>s+x.value*cdi*(x.cdi/100),0);
$('#currentMonth').textContent=selectedDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});setCurrencyValues();$('#cdiRate').value=b.cdiRate||'';$('#freeToSpend').textContent=money(free);$('#freeToSpendNote').textContent=free>=0?'Dentro do seu planejamento':'Você ultrapassou o planejamento';$('#budgetProgress').style.width=`${Math.min(100,Math.max(0,variable/Math.max(1,income-b.savingGoal-fixed)*100))}%`;$('#savingGoalValue').textContent=money(b.savingGoal);$('#savingStatus').textContent=income?`${money(fixed+variable)} comprometidos este mês`:'Defina sua renda para começar';$('#incomeTotal').textContent=money(income);$('#fixedTotal').textContent=money(fixed);$('#variableTotal').textContent=money(variable);$('#totalInvested').textContent=money(invested);$('#investmentReturn').textContent=`Rendimento mensal estimado: ${money(returns)}`;$('#syncState').textContent=config.url?'Planilha conectada':'Somente neste dispositivo';
renderList('fixedList','fixedEmpty',data.fixed,x=>row(x,`Vencimento dia ${x.day||'—'}`,'fixed'));renderList('expenseList','expenseEmpty',thisMonth(data.expenses).sort((a,b)=>b.created-a.created),x=>row(x,x.category||'Gasto livre','expenses'));renderList('incomeList','incomeEmpty',thisMonth(data.incomes).sort((a,b)=>b.created-a.created),x=>row(x,x.category||'Entrada extra','incomes',true));
$('#investmentList').innerHTML=data.investments.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${money(x.value)}</td><td>${x.cdi}%</td><td>${money(x.value*cdi*(x.cdi/100))}</td><td><button class="delete" onclick="removeItem('investments','${x.id}')">×</button></td></tr>`).join('');$('#investmentEmpty').style.display=data.investments.length?'none':'block'}
function setCurrencyValues(){[['salary','salary'],['savingGoal','savingGoal'],['otherIncome','otherIncome']].forEach(([el,prop])=>{$('#'+el).value=data.budget[prop]?money(data.budget[prop]):''})}function row(x,sub,type,positive=false){return `<div class="list-row"><i class="category-dot ${positive?'income-dot':''}"></i><div><strong>${esc(x.name)}</strong><small>${esc(sub)}</small></div><span class="value ${positive?'positive':''}">${positive?'+ ':''}${money(x.value)}</span><button class="delete" onclick="removeItem('${type}','${x.id}')">×</button></div>`}function renderList(list,emptyId,items,fn){$('#'+list).innerHTML=items.map(fn).join('');$('#'+emptyId).style.display=items.length?'none':'block'}function esc(v){return String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}window.removeItem=(type,itemId)=>{data[type]=data[type].filter(x=>x.id!==itemId);persist()};
function modal(type){const defs={fixed:[['name','Nome da conta','text'],['value','Valor mensal','currency'],['day','Dia de vencimento','number']],expense:[['name','Descrição','text'],['value','Valor','currency'],['category','Categoria (opcional)','text']],income:[['name','Descrição da entrada','text'],['value','Valor recebido','currency'],['category','Origem (opcional)','text']],investment:[['name','Nome do investimento','text'],['value','Valor aplicado','currency'],['cdi','% do CDI','decimal']]};$('#modalTitle').textContent={fixed:'Adicionar conta fixa',expense:'Lançar gasto',income:'Lançar entrada',investment:'Adicionar investimento'}[type];$('#modalFields').innerHTML=defs[type].map(([n,l,t])=>`<label>${l}<input required name="${n}" class="${t==='currency'?'currency':''}" inputmode="${t==='text'?'text':'decimal'}" placeholder="${t==='currency'?'R$ 0,00':''}"></label>`).join('');$('#entryForm').dataset.type=type;$('#entryModal').showModal()}
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity()){form.reportValidity();return}const f=new FormData(form),type=form.dataset.type,item={id:id(),name:f.get('name'),value:number(f.get('value'))};if(type==='fixed')item.day=f.get('day');if(type==='expense'||type==='income'){item.category=f.get('category');item.month=key();item.created=Date.now()}if(type==='investment')item.cdi=number(f.get('cdi'))||100;const store={expense:'expenses',income:'incomes',investment:'investments'}[type]||type;data[store].push(item);$('#entryModal').close();persist();toast('Registro salvo com sucesso.')});
function formatInput(e){if(e.target.value)e.target.value=money(number(e.target.value))}document.addEventListener('focusout',e=>{if(e.target.matches('.currency'))formatInput(e)});document.addEventListener('focusin',e=>{if(e.target.matches('.currency')&&e.target.value)e.target.value=String(number(e.target.value)).replace('.',',')});
$('#saveBudget').onclick=()=>{['salary','savingGoal','otherIncome'].forEach(p=>data.budget[p]=number($('#'+p).value));persist();toast('Planejamento atualizado.')};$('#updateCdi').onclick=()=>{data.budget.cdiRate=number($('#cdiRate').value);persist();toast('Taxa CDI atualizada.')};$('#addFixed').onclick=()=>modal('fixed');$('#addExpense').onclick=()=>modal('expense');$('#addIncome').onclick=()=>modal('income');$('#addInvestment').onclick=()=>modal('investment');$('#previousMonth').onclick=()=>{selectedDate.setMonth(selectedDate.getMonth()-1);render()};$('#nextMonth').onclick=()=>{selectedDate.setMonth(selectedDate.getMonth()+1);render()};['closeModal','cancelEntry'].forEach(x=>$('#'+x).onclick=()=>$('#entryModal').close());
$('#openSettings').onclick=()=>{$('#scriptUrl').value=config.url||'';$('#syncToken').value=config.token||'';$('#settingsModal').showModal()};['closeSettings'].forEach(x=>$('#'+x).onclick=()=>$('#settingsModal').close());$('#disconnect').onclick=()=>{config={};localStorage.removeItem(CONFIG);$('#settingsModal').close();render();toast('Sincronização desconectada.')};$('#settingsForm').onsubmit=e=>{e.preventDefault();config={url:$('#scriptUrl').value.replace(/\/$/,''),token:$('#syncToken').value};localStorage.setItem(CONFIG,JSON.stringify(config));$('#settingsModal').close();syncLoad()};
function jsonp(action,payload={}){return new Promise((resolve,reject)=>{const callback='mf'+Date.now()+Math.random().toString(36).slice(2),script=document.createElement('script'),params=new URLSearchParams({action,token:config.token,callback,...payload});const timer=setTimeout(()=>done(null,new Error('Tempo de conexão esgotado.')),15000);function done(result,error){clearTimeout(timer);delete window[callback];script.remove();error?reject(error):resolve(result)}window[callback]=r=>done(r);script.onerror=()=>done(null,new Error('Não foi possível acessar o Apps Script.'));script.src=`${config.url}?${params}`;document.head.append(script)})}
async function syncLoad(){if(!config.url||!config.token)return;toast('Sincronizando dados...');try{const r=await jsonp('get');if(!r.ok)throw Error(r.error);if(r.data&&Object.keys(r.data).length){data={...empty,...r.data};localStorage.setItem(KEY,JSON.stringify(data));render();toast('Dados da planilha sincronizados.')}else{await syncSave();toast('Planilha iniciada com seus dados.')}}catch(e){toast(`Erro de sincronização: ${e.message}`)}}function syncSave(){if(!config.url||!config.token)return Promise.resolve();return new Promise((resolve,reject)=>{const frame=document.createElement('iframe'),form=document.createElement('form'),timer=setTimeout(()=>{cleanup();reject(Error('Tempo de conexão esgotado.'))},15000);frame.name='meuFluxoSyncFrame';frame.hidden=true;form.method='POST';form.action=config.url;form.target=frame.name;form.hidden=true;[['action','save'],['token',config.token],['payload',btoa(unescape(encodeURIComponent(JSON.stringify(data))))]].forEach(([name,value])=>{const input=document.createElement('input');input.name=name;input.value=value;form.append(input)});function cleanup(){clearTimeout(timer);frame.remove();form.remove()}frame.onload=()=>{setTimeout(()=>{cleanup();resolve()},500)};document.body.append(frame,form);form.submit()})}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500)}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));render();if(config.url&&config.token)syncLoad();
